/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import db.DBAuthentication;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import javax.swing.BorderFactory;

/**
 *
 * @author vladv
 */
public class LoginFrame extends javax.swing.JFrame {
    boolean isAuthSucces = false;
   
    public LoginFrame() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("ConnHealth");
        loginErrortxt.setVisible(false);
        
        loginUsernameField.setBorder(BorderFactory.createCompoundBorder(loginUsernameField.getBorder(), BorderFactory.createEmptyBorder(0,11,0,0)));
        loginPasswordField.setBorder(BorderFactory.createCompoundBorder(loginUsernameField.getBorder(), BorderFactory.createEmptyBorder(0,4,0,0)));
        loginButtontxt.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                loginButtontxt.setEnabled(false);
                 checkData();
                 
                   
                 
                 
            }

            @Override
            public void mousePressed(MouseEvent e) {
               checkData();
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                //mouse released
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                loginButtontxt.setOpaque(true);
                loginButtontxt.setForeground(new Color(255,255,255));
                
            }

            @Override
            public void mouseExited(MouseEvent e) {
                 loginButtontxt.setOpaque(false);
                 loginButtontxt.setForeground(new Color(254,254,254));
                
            }
            
            
            public void checkData(){
                String username = loginUsernameField.getText().trim();
                String password = loginPasswordField.getText();
                if(username.isEmpty() || password.isEmpty()){
                    loginErrortxt.setVisible(true);
                    loginButtontxt.setEnabled(true);
                }
                else{
                    
                    
                    
                    boolean result = DBAuthentication.hasAccess(username, password);
                    if(result){
                        loginErrortxt.setVisible(false);
                        isAuthSucces();
                       
                    }
                    
                    else{
                        loginErrortxt.setVisible(true);
                        loginButtontxt.setEnabled(true);
                    } 
                }
                
                
                
                
            }
        });
        
        
       
    }
    
        public void isAuthSucces(){
            if(isAuthSucces==false){
                isAuthSucces=true;
                MainFrame mainFrame = new MainFrame();
                this.dispose();
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginGradientBackground = new keeptoo.KGradientPanel();
        loginPageTitletxt = new javax.swing.JLabel();
        loginUsernametxt = new javax.swing.JLabel();
        loginUsernameField = new javax.swing.JTextField();
        loginPasswordtxt = new javax.swing.JLabel();
        loginPasswordField = new javax.swing.JPasswordField();
        loginButtontxt = new javax.swing.JLabel();
        loginErrortxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 700));

        loginGradientBackground.setkEndColor(new java.awt.Color(38, 160, 218));
        loginGradientBackground.setkGradientFocus(0);
        loginGradientBackground.setkStartColor(new java.awt.Color(49, 71, 85));

        loginPageTitletxt.setFont(new java.awt.Font("Segoe UI", 0, 72)); // NOI18N
        loginPageTitletxt.setForeground(new java.awt.Color(255, 255, 255));
        loginPageTitletxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginPageTitletxt.setText("ConnHealth");
        loginPageTitletxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        loginUsernametxt.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        loginUsernametxt.setForeground(new java.awt.Color(255, 255, 255));
        loginUsernametxt.setText("Username:");

        loginUsernameField.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        loginUsernameField.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        loginUsernameField.setForeground(new java.awt.Color(255, 255, 255));
        loginUsernameField.setBorder(null);
        loginUsernameField.setCaretColor(new java.awt.Color(224, 222, 222));
        loginUsernameField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        loginUsernameField.setOpaque(false);
        loginUsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUsernameFieldActionPerformed(evt);
            }
        });

        loginPasswordtxt.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        loginPasswordtxt.setForeground(new java.awt.Color(255, 255, 255));
        loginPasswordtxt.setText("Password:");

        loginPasswordField.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        loginPasswordField.setForeground(new java.awt.Color(255, 255, 255));
        loginPasswordField.setBorder(null);
        loginPasswordField.setCaretColor(new java.awt.Color(255, 255, 255));
        loginPasswordField.setDisabledTextColor(new java.awt.Color(229, 229, 229));
        loginPasswordField.setMinimumSize(new java.awt.Dimension(6, 32));
        loginPasswordField.setName(""); // NOI18N
        loginPasswordField.setOpaque(false);
        loginPasswordField.setPreferredSize(new java.awt.Dimension(147, 32));

        loginButtontxt.setBackground(new java.awt.Color(46, 109, 148));
        loginButtontxt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        loginButtontxt.setForeground(new java.awt.Color(254, 254, 254));
        loginButtontxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginButtontxt.setText("Proceed");

        loginErrortxt.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        loginErrortxt.setForeground(new java.awt.Color(255, 255, 255));
        loginErrortxt.setText("Username or password are invalid!");

        javax.swing.GroupLayout loginGradientBackgroundLayout = new javax.swing.GroupLayout(loginGradientBackground);
        loginGradientBackground.setLayout(loginGradientBackgroundLayout);
        loginGradientBackgroundLayout.setHorizontalGroup(
            loginGradientBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginGradientBackgroundLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(loginGradientBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginGradientBackgroundLayout.createSequentialGroup()
                        .addComponent(loginErrortxt)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(loginGradientBackgroundLayout.createSequentialGroup()
                        .addGroup(loginGradientBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginUsernametxt)
                            .addComponent(loginPasswordtxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(loginGradientBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(loginUsernameField)
                            .addComponent(loginPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
                        .addGap(372, 372, 372))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginGradientBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginGradientBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginGradientBackgroundLayout.createSequentialGroup()
                        .addComponent(loginButtontxt, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginGradientBackgroundLayout.createSequentialGroup()
                        .addComponent(loginPageTitletxt, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(299, 299, 299))))
        );
        loginGradientBackgroundLayout.setVerticalGroup(
            loginGradientBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginGradientBackgroundLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(loginPageTitletxt, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addGroup(loginGradientBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginUsernametxt)
                    .addComponent(loginUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginGradientBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginPasswordtxt)
                    .addComponent(loginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(loginErrortxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(loginButtontxt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginGradientBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginGradientBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginUsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUsernameFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel loginButtontxt;
    private javax.swing.JLabel loginErrortxt;
    private keeptoo.KGradientPanel loginGradientBackground;
    private javax.swing.JLabel loginPageTitletxt;
    private javax.swing.JPasswordField loginPasswordField;
    private javax.swing.JLabel loginPasswordtxt;
    private javax.swing.JTextField loginUsernameField;
    private javax.swing.JLabel loginUsernametxt;
    // End of variables declaration//GEN-END:variables
}
